# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 662806e32fff76a9eed8f029ac46749dc87365a0603f0b923acbc7c3478123c74bd068e6538571aa344f951dd63801997679cf07a8846fa0e56e380afac3a76c

test:
  secret_key_base: d6934aa5219b9280baac82db1f33658a838fce41ac87c827dddf6b716dd25585e96836c1d9e1958f85ebd6722346c9d9bc691a167a860120bc380aa126841dc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
